INSERT INTO filmesdb.filme (genero,titulo,ano,descricao,link_img,link_trailer) VALUES
	 ('Drama','A Lenda de Oppenheimer',2024,'A história da vida de J. Robert Oppenheimer e seu papel no desenvolvimento da bomba atômica.','https://p2.trrsf.com/image/fget/cf/774/0/images.terra.com/2023/07/24/1867393537-oppenheimer-1.jpg','https://www.youtube.com/embed/F3OxA9Cz17A?si=O5dh4RbqDJ05QLS_'),
	 ('Ficção Científica','Avatar 3',2024,'Jake Sully e Neytiri enfrentam novos desafios em Pandora enquanto protegem sua família.','https://cinepop.com.br/wp-content/uploads/2023/03/avatar3_1.jpg','https://www.youtube.com/embed/BNyE47jbgwg?si=FsB8ufsur7K3a7ig'),
	 ('Animação','Frozen 3',2024,'Elsa e Anna enfrentam novas aventuras e mistérios enquanto exploram um reino distante.','https://cinepop.com.br/wp-content/uploads/2020/06/frozen-3.png','https://www.youtube.com/embed/xJgAypHXCZo?si=nkpsQn308A-Rt2H4'),
	 ('Terror','Invocação do Mal 4',2025,'Ed e Lorraine Warren investigam um novo caso paranormal aterrorizante.','https://media.fstatic.com/jhUMkITZ5X0YcE_99S3lwyGO_y4=/322x478/smart/filters:format(webp)/media/movies/covers/2013/04/d0b7c5c989e1717f4c27431f9c11ad47.jpg','https://www.youtube.com/embed/T_RJFveZBdI?si=RFHfAsGbix2xD6ET'),
	 ('Comédia','Super Mario Bros: O Filme 2',2023,'Mario e Luigi voltam a enfrentar novos vilões e aventuras no mundo dos videogames.','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAKfQbpMr0FNLZO97rYs4XrqxIXkSRfSS9eA&s','https://www.youtube.com/embed/0mqnkKgLT64?si=aXmgAmYVSYDiTyXG'),
	 ('Suspense','O Homem da Máscara de Ferro',1998,'Um detetive investiga uma série de assassinatos misteriosos ligados a uma figura mascarada.','https://br.web.img2.acsta.net/pictures/210/100/21010008_20130603220024666.jpg','https://www.youtube.com/embed/gnNt7l2nA_o?si=EHK1EnDBsj13-q2o'),
	 ('Aventura','Jumanji:Próxima Fase ',2017,'Um novo grupo de amigos entra no jogo Jumanji e enfrenta desafios ainda mais perigosos.','https://upload.wikimedia.org/wikipedia/pt/0/0d/Jumanji_The_Next_Level.jpg','https://www.youtube.com/embed/PEuMN4_lnPs?si=sjFFWoISVLE7rQ5K'),
	 ('Ficção Científica','Duna 2',2024,'Paul Atreides enfrenta novos inimigos e desafios enquanto luta pelo controle de Arrakis.','https://p2.trrsf.com/image/fget/cf/1200/1200/middle/images.terra.com/2024/04/01/973522750-duna-parte-2-poster-divulgacao.jpg','https://www.youtube.com/embed/QqmbrvluQRA?si=PcuB3X5fh706b8HK'),
	 ('Drama','O Último Jogo',2020,'Um time de jogadores se vê enfrentando as consequências de uma partida que mudou suas vidas.','https://assets.pandorafilmes.com.br/wp-content/uploads/2019/12/cartaz-O-iuLTIMO-JOGO-63x93-3Mega-min.jpg','https://www.youtube.com/embed/lLmPeKWi788?si=CwTMTA9LJO1Eluri'),
	 ('Romance','Em Algum Lugar do Amor',1980,'Dois corações se encontram enquanto enfrentam os desafios da vida moderna e do amor.','https://play-lh.googleusercontent.com/Gr06WgMWfBS1vMQTSFUHHadNnVr_x4CpXzg3xRKBJ98Yn1LatpeOiYakVtDs-nz8jZA=w240-h480-rw','https://www.youtube.com/embed/ZlhwDi7tIC8?si=RcfVQlpQ5peD1IW_');
INSERT INTO filmesdb.filme (genero,titulo,ano,descricao,link_img,link_trailer) VALUES
	 ('Ação','Vingadores 5',2025,'Os Vingadores reúnem suas forças para enfrentar uma ameaça cósmica que pode destruir o universo.','https://legadodamarvel.com.br/wp-content/uploads/2024/08/vingadores-5-poster-incrivel-epico-legadodamarvel.webp','https://www.youtube.com/embed/7PHgK-Apzno?si=A20u7KC1Aha6_B0v'),
	 ('Terror','A Casa Assombrada ',2021,'Uma jovem família se muda para uma casa misteriosa, onde forças sobrenaturais começam a ameaçar suas vidas.','https://m.media-amazon.com/images/S/pv-target-images/7c6c7f6042d9b69a27eec9a31d14d0b00fba23f3cecc18f2014133986e1e4554.jpg','https://www.youtube.com/embed/Mz88ZqkI97M?si=D68_XxXJ0FLN1EYS'),
	 ('Drama','O Último Desejo',2013,'Um drama sobre as escolhas da vida e os sacrifícios feitos por amor e ambição.','https://br.web.img3.acsta.net/c_310_420/pictures/14/06/10/23/35/426559.jpg','https://www.youtube.com/embed/Bt8Fx5seMZk?si=6OEGL1Aj4ITvyR2u'),
	 ('Aventura','Indiana Jones 5',2023,'O icônico arqueólogo e aventureiro Indiana Jones embarca em sua última jornada épica.','https://s2-gshow.glbimg.com/b3tM9Wk1CsK-MotBtuCQGJXJ_IQ=/1200x/smart/filters:cover():strip_icc()/i.s3.glbimg.com/v1/AUTH_e84042ef78cb4708aeebdf1c68c6cbd6/internal_photos/bs/2023/R/c/XgmlycRJmWxaJIIQOndQ/poster-indiana-jones-divulgacao.jpg','https://www.youtube.com/embed/j3_vrs8sH5k?si=qksp7RcAPnB7YOUg'),
	 ('Suspense','O Jogo da Mentira',2013,'Uma série de mentiras começa a desmoronar quando um simples jogo se torna uma questão de vida ou morte.','https://m.media-amazon.com/images/I/81-om46Ye7L._AC_UF1000,1000_QL80_.jpg','https://www.youtube.com/embed/CQRWRt2gJDM?si=mUCiQk6EuZl9yjYI" title="YouTube video player'),
	 ('Drama','Um Sonho de Liberdade',1994,'A emocionante história de esperança, amizade e superação dentro de uma prisão de segurança máxima.','https://m.media-amazon.com/images/I/51NiGlapXlL._AC_.jpg','<iframe width="560" height="315" src="https://www.youtube.com/embed/Y22NgkErOAk?si=MNSPgMUxHrd5ZHU9" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" r'),
	 ('Crime','Pulp Fiction: Tempo de Violência',1994,'Histórias interligadas do submundo do crime, cheias de diálogos memoráveis e ação.','https://m.media-amazon.com/images/I/71c05lTE03L._AC_SL1111_.jpg','https://www.youtube.com/embed/im-vRitDbTk?si=fheJfQ49SbYNRyF7'),
	 ('Ficção Científica','Matrix',1999,'Um hacker descobre a verdade sobre o mundo e lidera uma revolução contra máquinas opressoras.','https://m.media-amazon.com/images/I/51EG732BV3L._AC_.jpg','https://www.youtube.com/embed/vKQi3bBA1y8?si=ehAiGJHL6MtmjgH4'),
	 ('Fantasia','O Senhor dos Anéis: A Sociedade do Anel',2001,'Uma jornada épica para destruir o Um Anel e salvar a Terra-Média.','https://br.web.img3.acsta.net/medias/nmedia/18/92/91/32/20224832.jpg','https://www.youtube.com/embed/oPwvcWPh3LM?si=pNVXJyykYAvWj6mR'),
	 ('Ação','Vingadores: Ultimato',2019,'Os Vingadores se unem para reverter os eventos catastróficos de Thanos.','https://br.web.img3.acsta.net/pictures/19/04/26/17/30/2428965.jpg','https://www.youtube.com/embed/PgrmbRID0eY?si=oI0t-GC4N_28Elzb');
